[project]
name = "folly"
version = "0.1.0"
description = ""
authors = [
    {name = "ae",email = "85891169+novitae@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
]


[build-system]
requires = ["setuptools", "cython"]
build-backend = "setuptools.build_meta"


[tool.poetry.group.dev.dependencies]
setuptools = "^75.8.0"
cython = "^3.0.12"
pathlib = "^1.0.1"


[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"


[tool.poetry.group.build.dependencies]
requests = "^2.32.3"

[tool.pytest.ini_options]
addopts = '--ignore=folly/python/test/setup.py'
python_files = ["folly/python/test/*.py"]