# This package was generated using the repository
# https://github.com/novitae/pyfolly to facilitate the installation of
# Folly as a Python package.

# License and Copyright
# ---------------------
# All original source code included in this package is:

# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# How This Package Was Created
# ----------------------------
# This package was generated by directly copying files from the 
# official Folly repository, structuring them in a way that 
# allows for a seamless Python installation and build process.

# The goal of this repository is solely to provide an easy 
# way to install Folly as a Python package while maintaining 
# respect for Meta's original licensing and intellectual property.

# For any inquiries or issues regarding the original code,
# please refer to the official Folly repository:
# https://github.com/facebook/folly