name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.12, 3.13]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          poetry-version: 'latest'

      - name: Install dependencies
        run: poetry install --all-groups

      - name: Downloading folly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: poetry run python3 ./download.py

      - name: Building folly
        run: |
          FOLLY_SOURCE_DIR=$(find . -maxdepth 1 -type d -name 'folly-source-*' | head -n 1)
          if [ -z "$FOLLY_SOURCE_DIR" ]; then
            echo "Error: No directory matching 'folly-source-*' found."
            exit 1
          fi
          cd FOLLY_SOURCE_DIR
          poetry run python3 ./build/fbcode_builder/getdeps.py build
          FOLLY_BUILD_DIR=$(poetry run python3 ./build/fbcode_builder/getdeps.py show-inst-dir)
          cd ..
          echo "FOLLY_BUILD_DIR=$FOLLY_BUILD_DIR" >> $GITHUB_ENV

      - name: Build (main build)
        env:
          FOLLY_BUILD_DIR: $FOLLY_BUILD_DIR
        run: poetry run python setup.py build_ext --inplace

      - name: Test (depends on build)
        env:
          FOLLY_BUILD_DIR: $FOLLY_BUILD_DIR
        run: |
          cd ./folly/python/test
          poetry run python setup.py build_ext --inplace
          cd ../../..
          poetry run pytest